### ISSUE TITLE
latest powershell required

### ISSUE THREAD

**Issue by jardaKarlik** [iricigor/GetFolderAge#22]
I notice that the latest version of powershell is required to run this, which might not be possible for some enterprise environments. Can this requirement be removed??

**Comment by iricigor** [comment]
Please download new script from branch PS2Compatibility (or [this link](https://raw.githubusercontent.com/iricigor/GetFolderAge/PS2Compatibility/Get-FolderAge.ps1)) and let me know if the issue persists. On my system with PS v2, it runs fine, though I cannot run full tests against this version (testing system incompatibility).

**Comment by iricigor** [comment]
@jardaKarlik  PR merged, we can reopen this it if not working
