### ISSUE TITLE
script cant handle long path 

### ISSUE THREAD

**Issue by jardaKarlik** [iricigor/GetFolderAge#43]
got this error when script came to a file with "too long" path 

PS D:\Scripts> Get-FolderAge -folder v:\ > D:\Scripts\outputVonlyNewFile.txt
Get-ChildItem : Cannot find path 'v:\DATA\EUX Service Delivery Switzerland\MPS Service Delivery\Knowledge Management\Managed Print Services (EUS Sharepoint Dump)\MPS
Printing Technology\HP Transition DVDs\DVD1_TS_Jan_31_2012\Documents\Device and Driver Qualification\Device Qualification\Scanned Device Qualification Documents'
because it does not exist.
At D:\Scripts\Get-FolderAge.ps1:212 char:33
+                     $Children = Get-ChildItem -LiteralPath $queue[$i]
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (v:\DATA\EUX Ser...ation Documents:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by iricigor** [comment]
Thanks for reporting it! Will handle it asap.

**Comment by iricigor** [comment]
first idea: commit 90ab9b515c3bac5b8900e94bc757b35146da6fe7
