### ISSUE TITLE
-Exclude supports only one folder

### ISSUE THREAD

**Issue by inti-F82** [iricigor/GetFolderAge#82]
Hi, 

I'm able to exclude only one folder with -Exclude. 
Please modify the -Exclude part, so that I'll be able to exclude multiple folders. 

Thanks.

**Comment by iricigor** [comment]
Hi, it should work if you specify a comma separated list of folder names, but I will test it more. I will add test for it and examples in readme.

```PowerShell
Get-FolderAge -FolderName .. -Exclude .git,GetFolderAge
```
